### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by sergani** [kolypto/py-mailem#2]
Hello,

I installed the mailem package using _pip_ once and _setup.py_ another time. Both installations result in the demo example not working.

This is the error I receive:

```
Traceback (most recent call last):
  File "test_email.py", line 1, in <module>
    from mailem import Message, Postman, Attachment, ImageAttachment
  File "/usr/lib/python2.6/site-packages/mailem-0.0.3_1-py2.6.egg/mailem/__init__.py", line 55, in <module>
    from .message import Message
  File "/usr/lib/python2.6/site-packages/mailem-0.0.3_1-py2.6.egg/mailem/message.py", line 106
    for key, addresses in (
      ^
SyntaxError: invalid syntax
```

This is my example:

```
from mailem import Message, Postman, Attachment, ImageAttachment
from mailem.connection import SMTPConnection

messages = [
Message(
        ['me@domain.com'],
        u"Mail'em test with inline images",
        u"Cute: <img src='cid:image.png' />",  # cid:<filename>
        attachments = [
            ImageAttachment('image.png', open('image.png').read(), 'inline')
        ]
    ),
]

# Initialize a postman with SMTP connection to GMail
postman = Postman('me@gmail.com',
                  SMTPConnection(
                      'smtp.gmail.com', 587,
                      'me@gmail.com', 'p@$$',
                      tls=True
                  ))

with postman.connect() as c:
    map(c.sendmail, messages)
```

**Comment by sergani** [comment]
Apologies, seems the issue is with my Python 2.6.
Is it possible to provide support for Python 2.6?

**Comment by kolypto** [comment]
@sergani , sorry for the delayed response. is Python 2.6 support still relevant?
I am not currently planning to support obsolete Python versions.
